
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "BUILD_SHARED_LIBS" "=" "${BUILD_SHARED_LIBS}")
#   message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} root" "BUILD_STATIC_LIBS" "=" "${BUILD_STATIC_LIBS}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "LIBRARY_PREFIX" "=" "${LIBRARY_PREFIX}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "LIBRARY_SUFFIX" "=" "${LIBRARY_SUFFIX}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_BINARY_DIR" "=" "${CMAKE_BINARY_DIR}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_CURRENT_BINARY_DIR" "=" "${CMAKE_CURRENT_BINARY_DIR}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_ARCHIVE_OUTPUT_DIRECTORY" "=" "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_LIBRARY_OUTPUT_DIRECTORY" "=" "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_RUNTIME_OUTPUT_DIRECTORY" "=" "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "${PROJECT_NAME_UPPER}_ARCHIVE_OUTPUT_DIRECTORY"    "=" "${${PROJECT_NAME_UPPER}_ARCHIVE_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "${PROJECT_NAME_UPPER}_LIBRARY_OUTPUT_DIRECTORY"    "=" "${${PROJECT_NAME_UPPER}_LIBRARY_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "${PROJECT_NAME_UPPER}_RUNTIME_OUTPUT_DIRECTORY"    "=" "${${PROJECT_NAME_UPPER}_RUNTIME_OUTPUT_DIRECTORY}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_GENERATOR:INTERNAL" "=" "${CMAKE_GENERATOR}")
message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} module" "CMAKE_BUILD_TYPE" "=" "${CMAKE_BUILD_TYPE}")
#    message_format (STATUS "${lead_mark_location}" "${PROJECT_NAME} root" "feature_summary *****************************")
#    feature_summary(WHAT ALL FATAL_ON_MISSING_REQUIRED_PACKAGES)
